to use this configuration, you should download this file and copy to /etc/X11/xorg.conf.d/ directory with sudo and dont forget to remove this line.

Section "InputClass"
  Identifier "touchpad"
  Driver "libinput"
  MatchIsTouchpad "on"
  Option "Tapping" "on"
  Option "ScrollMethod" "twofinger"
  Option "NaturalScrolling" "true"
  Option "DisableWhileTyping" "true"
  Option "ClickMethod" "clickfinger"
EndSection
